p=('python','c','java','html','css','angularjs','mongodb')
print(p)
print("maximum number:",max(p))
print("minimum number:",min(p))
print("sorted tuple:",sorted(p))
print("length of tuple:",len(p))
print("reversed tuple :",p[::-1])
